# Generated by Django 3.0.5 on 2022-06-25 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0019_auto_20220625_1601'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='department',
            field=models.CharField(choices=[('Emergency Medicine Specialists', 'Emergency Medicine Specialists'), ('Medical Consultants', 'Medical Consultants'), ('Cardiologist', 'Cardiologist'), ('Dermatologists', 'Dermatologists'), ('Physician', 'Physician'), ('Ophthamologist', 'Ophthamologist'), ('Dentist', 'Dentist'), ('ENT Specialist', 'ENT Specialist'), ('Gastroentrologists', 'Gastroentrologists')], default='Cardiologist', max_length=50),
        ),
    ]
