# Generated by Django 4.0.1 on 2022-06-25 22:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0020_auto_20220625_1604'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PatientDischargeDetails',
        ),
    ]
